/**
 * 쿠팡 쉽먼트 생성 페이지의 `#deliveryCompany` select option 목록.
 * 사이트 HTML 에서 그대로 덤프 — value 는 쿠팡 내부 코드, label 은 표시명.
 *
 * 유지 보수:
 *   사이트가 신규 택배사를 추가했으면 해당 페이지의 select 를 복사해 갱신.
 *   (지금은 2026-04 기준)
 */

export const DELIVERY_COMPANIES = [
  { value: '',           label: '(미지정)' },
  { value: 'D000001',    label: '롯데택배' },
  { value: 'D000002',    label: '로젠택배' },
  { value: 'D000003',    label: '우체국' },
  { value: 'D000004',    label: '한진택배' },
  { value: 'D000005',    label: '대한통운' },
  { value: 'D000006',    label: 'CJ 대한통운' },
  { value: 'D000008',    label: '경동택배' },
  { value: 'D000012',    label: '일양택배' },
  { value: 'D000013',    label: '천일특송' },
  { value: 'D000014',    label: '아주택배' },
  { value: 'D000015',    label: 'SC로지스' },
  { value: 'D000016',    label: '대신택배' },
  { value: 'D000017',    label: 'CVS택배' },
  { value: 'D000018',    label: '합동택배' },
  { value: 'D000020',    label: 'DHL' },
  { value: 'D000021',    label: 'UPS' },
  { value: 'D000022',    label: 'FEDEX' },
  { value: 'D999998',    label: '우편등기' },
  { value: 'D000023',    label: '우체국 EMS' },
  { value: 'TNT',        label: 'TNT' },
  { value: 'USPS',       label: 'USPS' },
  { value: 'IPARCEL',    label: 'i-parcel' },
  { value: 'GSMNTON',    label: 'GSM NtoN' },
  { value: 'SWGEXP',     label: '성원글로벌' },
  { value: 'PANTOS',     label: 'LX Pantos' },
  { value: 'ACIEXPRESS', label: 'ACI Express' },
  { value: 'DAEWOON',    label: '대운글로벌' },
  { value: 'AIRBOY',     label: '에어보이익스프레스' },
  { value: 'KGLNET',     label: 'KGL네트웍스' },
  { value: 'KUNYOUNG',   label: '건영택배' },
  { value: 'SLX',        label: 'SLX택배' },
  { value: 'HONAM',      label: '우리택배' },
  { value: 'LINEEXPRES', label: 'LineExpress' },
  { value: '2FASTEXP',   label: '2FastsExpress' },
  { value: 'hpl',        label: '한의사랑택배' },
  { value: 'goodstoluc', label: '굿투럭' },
  { value: 'korexg',     label: 'CJ대한통운특송' },
  { value: 'handex',     label: '한진국제특송' },
  { value: 'BGF',        label: 'BGF포스트' },
  { value: 'ECMS',       label: 'ECMS익스프레스' },
  { value: 'SELC',       label: '삼성직배송' },
  { value: 'SELC2',      label: '삼성직배송 (2)' },
  { value: 'WONDERS',    label: '원더스퀵' },
  { value: 'YONGMA',     label: '용마로지스' },
  { value: 'SEBANG',     label: '세방택배' },
  { value: 'NHLOGIS',    label: '농협택배' },
  { value: 'LOTTEGLOBA', label: '롯데글로벌' },
  { value: 'GSIEXPRESS', label: 'GSI익스프레스' },
  { value: 'EFS',        label: 'EFS' },
  { value: 'DHLGLOBALM', label: 'DHL GlobalMail' },
  { value: 'HILOGIS',    label: 'HI택배' },
  { value: 'GPSLOGIX',   label: 'GPS로직' },
  { value: 'CRLX',       label: '시알로지텍' },
  { value: 'BRIDGE',     label: '브리지로지스' },
  { value: 'HOMEINNOV',  label: '홈이노베이션로지스' },
  { value: 'CWAY',       label: '씨웨이' },
  { value: 'GNETWORK',   label: '자이언트' },
  { value: 'ACEEXP',     label: 'ACE Express' },
  { value: 'WEVILL',     label: '우리동네택배' },
  { value: 'FOREVERPS',  label: '퍼레버택배' },
  { value: 'WARPEX',     label: '워펙스' },
  { value: 'QXPRESS',    label: '큐익스프레스' },
  { value: 'SMARTLOGIS', label: '스마트로지스' },
  { value: 'SKMAGIC',    label: 'SK직배송' },
  { value: 'LGE',        label: 'LG전자' },
  { value: 'WINION',     label: 'CLS (WINION)' },
  { value: 'WINION2',    label: 'CLS (WINION2)' },
  { value: 'HOWSER',     label: '하우저' },
  { value: 'CJWATER',    label: 'CJ생수' },
  { value: 'OVERSEA',    label: 'OVERSEA' },
  { value: 'HOMEPICK',   label: '홈픽택배' },
  { value: 'GTSLOGIS',   label: 'GTS로지스' },
  { value: 'ESTHER',     label: '에스더쉬핑' },
  { value: 'INTRAS',     label: '로토스' },
  { value: 'EUNHA',      label: '은하쉬핑' },
  { value: 'UFREIGHT',   label: '유프레이트 코리아' },
  { value: 'LSERVICE',   label: '엘서비스' },
  { value: 'TPMLOGIS',   label: '로지스밸리택배' },
  { value: 'ZENIELSYST', label: '제니엘시스템' },
  { value: 'ANYTRACK',   label: '애니트랙' },
  { value: 'JLOGIST',    label: '제이로지스트' },
  { value: 'CHAINLOGIS', label: '두발히어로(4시간당일택배)' },
  { value: 'QRUN',       label: '큐런' },
  { value: 'FRESHSOLUT', label: '프레시솔루션' },
  { value: 'HIVECITY',   label: '하이브시티' },
  { value: 'HANSSEM',    label: '한샘' },
  { value: 'SFC',        label: 'SFC(Santai)' },
  { value: 'JNET',       label: 'J-NET' },
  { value: 'GENIEGO',    label: '지니고' },
  { value: 'PANASIA',    label: '판아시아' },
  { value: 'ELIAN',      label: 'elianpost' },
  { value: 'SAMSUNGAC',  label: '삼성에어컨직배송' },
  { value: 'NEXEN',      label: 'NEXEN직배송' },
  { value: 'EUGWATER',   label: '유진로지스틱스' },
  { value: 'LTL',        label: 'LTL' },
  { value: 'DADASMART',  label: '다다스마트' },
  { value: 'LOGISPOT',   label: '로지스팟' },
  { value: 'FRESHMATES', label: '프레시메이트' },
  { value: 'VROONG',     label: '부릉' },
  { value: 'NKLS',       label: 'NK로지솔루션' },
  { value: 'DODOFLEX',   label: '도도플렉스' },
  { value: 'ETOMARS',    label: '이투마스' },
  { value: 'SHIPNERGY',  label: '배송하기좋은날' },
  { value: 'VENDORPIA',  label: '벤더피아' },
  { value: 'COSHIP',     label: '캐나다쉬핑' },
  { value: 'GDAKOREA',   label: '지디에이코리아' },
  { value: 'BABABA',     label: '바바바로지스' },
  { value: 'TEAMFRESH',  label: '팀프레시' },
  { value: 'LOTTECHILS', label: '롯데칠성' },
  { value: 'SBGLS',      label: 'SBGLS' },
  { value: 'ALLTAKOREA', label: '올타코리아' },
  { value: 'YUNDA',      label: 'yunda express' },
  { value: 'VALEX',      label: '발렉스' },
  { value: 'KOKUSAI',    label: '국제익스프레스' },
  { value: 'XINPATEK',   label: '윈핸드해운상공' },
  { value: 'HEREWEGO',   label: '탱고앤고' },
  { value: 'WOONGJI',    label: '웅지익스프레스' },
  { value: 'PINGPONG',   label: '핑퐁' },
  { value: 'YDH',        label: 'YDH' },
  { value: 'CARGOPLEAS', label: '화물부탁해' },
  { value: 'HOME1004',   label: '1004홈' },
  { value: 'NAEUN',      label: '나은물류' },
  { value: 'ACCCARGO',   label: 'acccargo' },
  { value: 'NTLPS',      label: '엔티엘피스' },
  { value: 'EKDP',       label: '삼다수가정배송' },
  { value: 'HOTSINGCAR', label: '허싱카고코리아' },
  { value: 'SINOEX',     label: 'SINOTRANS EXPRESS' },
  { value: 'DRABBIT',    label: '딜리래빗' },
  { value: 'HOMEPICKTO', label: '홈픽오늘도착' },
  { value: 'DAERIM',     label: '대림통운' },
  { value: 'LOGISPARTN', label: '로지스파트너' },
  { value: 'GOBOX',      label: '고박스' },
  { value: 'FASTBOX',    label: '패스트박스' },
  { value: 'FANSTAR',    label: '팬스타국제특송(deprecated)' },
  { value: 'PANSTAR',    label: '팬스타국제특송' },
  { value: 'ACTCORE',    label: '에이씨티앤코아물류' },
  { value: 'KJT',        label: '케이제이티' },
  { value: 'THEBAO',     label: '더바오' },
  { value: 'RUSH',       label: '오늘회러쉬' },
  { value: 'KT',         label: 'kt express' },
  { value: 'IBP',        label: 'ibpcorp' },
  { value: 'HY',         label: 'HY' },
  { value: 'LOGISVALLE', label: '로지스밸리' },
  { value: 'TODAY',      label: '투데이' },
  { value: 'ONEDAYLOGI', label: '라스트마일시스템즈' },
  { value: 'HKHOLDINGS', label: '에이치케이홀딩스' },
  { value: 'JIKGUMOON',  label: '직구문' },
  { value: 'CUBEFLOW',   label: '큐브플로우' },
  { value: 'SHFLY',      label: '성훈물류' },
  { value: 'GBS',        label: '지비에스' },
  { value: 'BANPOOM',    label: '반품구조대' },
  { value: 'GLOVIS',     label: '현대글로비스' },
  { value: 'ARGO',       label: '아르고' },
  { value: 'FLEXPORT',   label: 'FLEXPORT' },
  { value: 'SAMSUNGSDS', label: '삼성SDS' },
  { value: 'JMNP',       label: '딜리박스' },
  { value: 'SELC3P',     label: '삼성로지텍' },
  { value: 'MTINTER',    label: '엠티인터네셔벌' },
  { value: 'GDSP',       label: '골드스넵스' },
  { value: 'TODAYPICK',  label: '오늘의픽업' },
  { value: 'YJSGLOBAL',  label: 'yjs글로벌' },
  { value: 'DUXGLOBAL',  label: '유로택배' },
  { value: 'INTERLOGIS', label: '인터로지스' },
  { value: 'WOOJIN',     label: '반얀로지스틱스' },
  { value: 'GHSPEED',    label: '지에이치스피드' },
  { value: 'WIDETECH',   label: '와이드테크' },
  { value: 'ECOHAI',     label: '에코하이' },
  { value: 'TONAMI',     label: '토나미' },
  { value: 'DAIICHI',    label: '제1화물' },
  { value: 'FUKUYAMA',   label: '후쿠야마통운' },
  { value: 'KURLYNEXT',  label: '컬리넥스트마일' },
  { value: 'ARAMEX',     label: 'ARAMEX' },
  { value: 'BISNZ',      label: 'BISNZ' },
  { value: 'INNOS',      label: '이노스' },
  { value: 'SEORIM',     label: '서림물류' },
  { value: 'WEMOVE',     label: '위무브' },
  { value: 'POOLATHOME', label: '풀앳홈' },
  { value: 'SPARKLE',    label: '스파클직배송' },
  { value: 'ICS',        label: 'ICS' },
  { value: 'HANMI',      label: '한미포스트' },
  { value: 'CAINIAO',    label: 'cainiao' },
  { value: 'HWATONG',    label: '화통' },
  { value: 'ESTLA',      label: '이스트라' },
  { value: 'IK',         label: 'IK물류' },
  { value: 'PMOWATER',   label: '풀무원샘물' },
  { value: 'TSG',        label: '티에스지로지스' },
  { value: 'OCS',        label: 'ocs코리아' },
  { value: 'DNDN',       label: '든든택배' },
  { value: 'MDLOGIS',    label: '모든로지스' },
  { value: 'GCS',        label: '지씨에스' },
  { value: 'FTF',        label: '물류대장LCS' },
  { value: 'HUBNET',     label: 'Hubnet Logistics' },
  { value: 'CASA',       label: '신세계까사' },
  { value: 'BRCH',       label: '비알씨에이치' },
  { value: 'HLDE',       label: 'W7' },
  { value: 'MORNINGGLO', label: '모닝글로벌' },
  { value: 'TW_YAMATO',  label: '黑貓宅急便 (TW)' },
  { value: 'TWL_YAMATO', label: '黑貓宅急便 (TWL)' },
  { value: 'TWL_POST',   label: '郵局' },
  { value: 'TWL_FM',     label: '全家' },
  { value: 'TWL_711',    label: '7-11' },
  { value: 'TWL_HCT',    label: '新竹物流' },
  { value: 'TW_KERRY',   label: '嘉里大榮 (TW)' },
  { value: 'TWL_KERRY',  label: '嘉里大榮 (TWL)' },
  { value: 'TWL_CPNG',   label: 'TWL_CPNG' },
  { value: 'TWL_OKMART', label: 'OK超商' },
  { value: 'TWL_TCAT',   label: '黑貓宅急便 (TCAT)' },
  { value: 'TWL_PLC',    label: '宅配通' },
  { value: 'CLS',        label: '쿠팡로지스틱스' },
  { value: 'CLS1',       label: '쿠팡로지스틱스 (CLS1)' },
  { value: 'CLS2',       label: '쿠팡로지스틱스 (CLS2)' },
  { value: 'CLS3',       label: '쿠팡로지스틱스 (CLS3)' },
  { value: 'CLS4',       label: '쿠팡로지스틱스 (CLS4)' },
  { value: 'CLS5',       label: '쿠팡로지스틱스 (CLS5)' },
  { value: 'CLS6',       label: '쿠팡로지스틱스 (CLS6)' },
  { value: '3PWINION',   label: '위니온로지스' },
  { value: 'WOORIHB',    label: '우리한방택배' },
  { value: 'LETUS',      label: '레터스' },
  { value: 'JWTNL',      label: 'JWTNL' },
  { value: 'TWL_SFX',    label: 'TWL_SFX' },
  { value: 'JCLS',       label: 'JCLS' },
  { value: 'GKGLOBAL',   label: '지케이글로벌' },
  { value: 'GONELO',     label: '고넬로' },
  { value: 'WSK',        label: 'WSK' },
  { value: 'RETURNALL',  label: '리터놀' },
  { value: 'ONTRAC',     label: 'OnTrac' },
  { value: 'HERMES',     label: 'Hermes' },
  { value: 'EMART24',    label: '이마트24' },
  { value: 'SEVENELEVE', label: '세븐일레븐' },
  { value: 'SUNYOUNG',   label: '生洋' },
  { value: 'SAGAWA',     label: '사가와' },
  { value: 'BAROS',      label: '바로스' },
  { value: 'MILKRUN',    label: '밀크런' },
];
