/**
 * 빌드 플레이버 준비 — BUILD_FLAVOR 에 따라
 * `src/plugins/_generated.js` 를 새로 생성한다.
 *
 *   basic  → 코어만 (플러그인 없음)
 *   tbnws  → tbnws 플러그인 포함
 *   (향후) acme, ...
 *
 * 핵심: flavor=basic 빌드의 webpack 번들에는 tbnws 폴더 import 자체가
 * 없으니 코드가 들어가지 않음 → 비구매자 바이너리에 노출 안 됨.
 *
 * 사용:
 *   node scripts/prepare-flavor.js tbnws
 *   BUILD_FLAVOR=basic node scripts/prepare-flavor.js
 *   (인자 없으면 dev 기본값 = tbnws)
 */

const fs = require('fs');
const path = require('path');

// 각 entry: 생성할 import path. 로컬은 './<dir>', 외부 패키지는 패키지명.
const FLAVORS = {
  basic: [],
  tbnws: ['coupang-supplier-plugin-tbnws'],
  // acme: ['coupang-supplier-plugin-acme'],
};

const flavor = process.argv[2] || process.env.BUILD_FLAVOR || 'tbnws';
const plugins = FLAVORS[flavor];
if (!plugins) {
  console.error(`[flavor] 알 수 없는 flavor: ${flavor}`);
  console.error(`[flavor] 사용 가능: ${Object.keys(FLAVORS).join(', ')}`);
  process.exit(1);
}

const imports = plugins
  .map((p, i) => `import m${i} from ${JSON.stringify(p)};`)
  .join('\n');
const arr = plugins.map((_, i) => `m${i}`).join(', ');

const content = `// AUTO-GENERATED by scripts/prepare-flavor.js (flavor=${flavor})
// 직접 편집 금지. .gitignore 됨. flavor 변경은 빌드 명령 인자로.
${imports}
export const MANIFESTS = [${arr}];
export const FLAVOR = ${JSON.stringify(flavor)};
`;

const out = path.resolve(__dirname, '..', 'src', 'plugins', '_generated.js');
fs.writeFileSync(out, content);
console.log(`[flavor] ${flavor} → [${plugins.join(', ') || '(none)'}]  ${path.relative(path.resolve(__dirname, '..'), out)}`);
